dotnetapp/Models/EmployeeModel.cs
using System;

namespace dotnetapp.Models
{
    public class Employee
    {
        public int id { get; set; }
        public string Name { get; set; }
        public DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
        public decimal salary { get; set; }
        public string Email { get; set; }
        public string phoneNumber { get; set; }
        public string Address { get; set; }
    }
}

dotnetapp/Models/ErrorViewModel.cs
namespace dotnetapp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

dotnetapp/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using dotnetapp.Models;
using System.Data;
using Microsoft.Data.SqlClient;


namespace dotnetapp.Controllers { 
public class EmployeeController : Controller
{
    private string connectionString = "User ID=sa;password=examlyMssql@123; server=localhost;Database=EmpDB;trusted_connection=false;Persist Security Info=False;Encrypt=False";

    public ActionResult Index()
    {
        List<Employee> employees = new List<Employee>();
try
{
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            string query = "SELECT * FROM Employee";
            using (SqlCommand command = new SqlCommand(query, connection))
            {
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                Employee employee = new Employee();
                employee.id = Convert.ToInt32(reader["id"]);                   
                employee.Name = reader["Name"].ToString();
                employee.DOB = Convert.ToDateTime(reader["DOB"]);
                employee.Gender = reader["Gender"].ToString();
                employee.Department = reader["Department"].ToString();
                employee.Position = reader["Position"].ToString();
                employee.salary = Convert.ToDecimal(reader["salary"]);
                employee.Email = reader["Email"].ToString();
                employee.phoneNumber = reader["phoneNumber"].ToString();
                employee.Address = reader["Address"].ToString();
                employees.Add(employee);
                }

                reader.Close();
            }
        } 
        return View(employees);
}
catch(Exception ex)
{
    Console.WriteLine(ex.Message);
    return BadRequest("An error occurred while retrieving the employee item.");

}
        // return View(employees);

    }
    public ActionResult Create()
    {
        return View();
    }
    
    
    [HttpPost]
    public ActionResult Create(Employee employee)
    {
        try{
        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            string query = "INSERT INTO Employee (Name, DOB, Gender, Department, Position, Salary, Email, phoneNumber,Address) VALUES (@Name, @DOB, @Gender, @Department, @Position, @Salary, @Email, @phoneNumber, @Address)";
            using (SqlCommand command = new SqlCommand(query, connection))
            {
                // command.Parameters.AddWithValue("@id", Employee.id);
                command.Parameters.AddWithValue("@Name", employee.Name);
                command.Parameters.AddWithValue("@DOB", employee.DOB);
                command.Parameters.AddWithValue("@Gender", employee.Gender);
                command.Parameters.AddWithValue("@Department", employee.Department);
                command.Parameters.AddWithValue("@Position", employee.Position);
                command.Parameters.AddWithValue("@salary", employee.salary);
                command.Parameters.AddWithValue("@Email", employee.Email);
                command.Parameters.AddWithValue("@phoneNumber", employee.phoneNumber);
                command.Parameters.AddWithValue("@Address", employee.Address);
                connection.Open();
                command.ExecuteNonQuery();
            }
        }
        }
        catch(Exception ex)
{
    Console.WriteLine(ex.Message);
            return BadRequest("An error occurred while creating the furniture item.");

}
        return RedirectToAction("Index");
    }



    public ActionResult Search(string query)
{
    try
    {
        List<Employee> employees = new List<Employee>();

        using (SqlConnection connection = new SqlConnection(connectionString))
        {
            string searchQuery = "SELECT * FROM Employee WHERE id LIKE @query OR Name LIKE @query";
            using (SqlCommand command = new SqlCommand(searchQuery, connection))
            {
                command.Parameters.AddWithValue("@query", "%" + query + "%"); // Wildcard search

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                while (reader.Read())
                {
                    Employee employee = new Employee();
                    employee.id = Convert.ToInt32(reader["id"]);
                    employee.Name = reader["Name"].ToString();
                    employee.DOB = DateTime.Parse(reader["DOB"].ToString());
                    employee.Gender = reader["Gender"].ToString();
                    employee.Department = reader["Department"].ToString();
                    employee.Position = reader["Position"].ToString();
                    employee.salary = Convert.ToDecimal(reader["Salary"]);
                    employee.Email = reader["Email"].ToString();
                    employee.phoneNumber = reader["phoneNumber"].ToString();
                    employee.Address = reader["Address"].ToString();
                    employees.Add(employee);
                }

                reader.Close();
            }
        }

        return View("Index", employees);
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.Message);
        return BadRequest("An error occurred while searching for employees.");
    }
}


}
    }

dotnetapp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using dotnetapp.Models;

namespace dotnetapp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

dotnetapp/Views/Employee/Create.cshtml
@model Employee

<h2>Create New Employee</h2>

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DOB)
        @Html.TextBoxFor(model => model.DOB, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Gender)
        @Html.TextBoxFor(model => model.Gender, new { @class = "form-control" })
    </div> 

    <div class="form-group">
        @Html.LabelFor(model => model.Department)
        @Html.TextBoxFor(model => model.Department, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Position)
        @Html.TextBoxFor(model => model.Position, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.salary)
        @Html.TextBoxFor(model => model.salary, new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
    </div> 

    <div class="form-group">
        @Html.LabelFor(model => model.phoneNumber)
        @Html.TextBoxFor(model => model.phoneNumber, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address)
        @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
    </div>

    <input type="submit" value="Create" class="btn btn-primary" />
}

dotnetapp/Views/Employee/Edit.cshtml
@model dotnetapp.Models.Employee

<h2>Edit Employee</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DOB)
        @Html.TextBoxFor(model => model.DOB, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Gender)
        @Html.TextBoxFor(model => model.Gender, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Department)
        @Html.TextBoxFor(model => model.Department, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Position)
        @Html.TextBoxFor(model => model.Position, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.salary)
        @Html.TextBoxFor(model => model.salary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.salary, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.phoneNumber)
        @Html.TextBoxFor(model => model.phoneNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
    </div>

     <div class="form-group">
        @Html.LabelFor(model => model.Address)
        @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
    </div>


    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

dotnetapp/Views/Employee/Index.cshtml
@model List<Employee>

<h2>Employee List</h2>

@using (Html.BeginForm("Search", "Employee", FormMethod.Get))
{
    <div class="input-group mb-3">
        <input type="text" name="query" class="form-control" placeholder="Search by ID or Name" aria-label="Search by ID or Name" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </div>
    </div>
}

<table class="table">
    <thead class="table">
        <tr>
            <th>Employee ID</th>
            <th>Name</th>
            <th>DOB</th>
            <th>Gender</th>
            <th>Department</th>
            <th>Position</th>
            <th>Salary</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Address</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var emp in Model)
        {
            <tr>
                <td>@emp.id</td>
                <td>@emp.Name</td>
                <td>@emp.DOB</td>
                <td>@emp.Gender</td>
                <td>@emp.Department</td>   
                <td>@emp.Position</td>
                <td>@emp.salary</td>
                <td>@emp.Email</td>
                <td>@emp.phoneNumber</td>
                <td>@emp.Address</td>
                
            </tr>
        }
    </tbody>
</table>

<a href="@Url.Action("Create")" class="btn btn-primary">Create New Employee</a>

dotnetapp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

dotnetapp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotnetapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotnetapp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotnetapp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - dotnetapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>